version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    container_name: wordpress-mysql
    networks:
      separate_ip_network:
        ipv4_address: 172.18.0.2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - ./mysql-data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      separate_ip_network:
        ipv4_address: 172.18.0.3
    environment:
      WORDPRESS_DB_HOST: 172.18.0.2
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DEBUG: "true"
      WORDPRESS_NAME: "site-1"
    volumes:
      - ./wp-content-site1:/var/www/html/wp-content
      - ./wp-themes-site1:/var/www/html/wp-content/themes
      - ./wp-plugins-site1:/var/www/html/wp-content/plugins
      - ./config/wp-config-site1.php:/var/www/html/wp-config.php
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    networks:
      separate_ip_network:
        ipv4_address: 172.18.0.4
    environment:
      PMA_HOST: 172.18.0.2
      PMA_USER: root
      PMA_PASSWORD: root_password
networks:
  separate_ip_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
